services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: cargahoras
      POSTGRES_PASSWORD: cargahoras_pass
      POSTGRES_DB: cargadehoras
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data